# -*- coding: utf-8 -*-
"""3a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZrv8BgfvxbUmi7fZM9uaX_Q8S0BsUUG
"""

#from google.colab import files
#upload1 = files.upload()

#upload2 = files.upload()



import pandas as pd
import json
import requests
import sys


file1 = sys.argv[1]
file2 = sys.argv[2]


db = requests.get("https://question-3a-default-rtdb.firebaseio.com/")

db

new_user= 'chats'

with open(file1) as f:
  chats = json.load(f)


chats

chat_url = "https://question-3a-default-rtdb.firebaseio.com/"+new_user+".json"
chat_url

chat_response = requests.put(url = chat_url, json =chats)

chat_response

with open(file2) as f:
  roster = json.load(f)

roster

new_user2 = 'roster'
roster_url = "https://question-3a-default-rtdb.firebaseio.com/"+new_user2+".json"

roster_response = requests.put(url = roster_url, json = roster)
print(roster_response)

