# -*- coding: utf-8 -*-
"""3b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ohlNEJj8hAmmXsIbbBNAze8_DnDjv_cj
"""

import json
import pandas as pd
#import firebase_admin as fb
import re
#import sys

import requests


keyword = input("Enter a name: ")

URL = "https://question-3a-default-rtdb.firebaseio.com/roster.json"

response = requests.get(URL)
data = json.loads(response.text)

data

df = pd.DataFrame(data, columns=['Name', 'Participating from'])

df

keyword = keyword.lower()
keyword

#if ' ' in keyword == True:
words = keyword.split(' ')
#
words

temp = []
def search_person(keyword, df):
    for i in range(len(words)):
        for k in range(len(df)):
            if re.search(words[i], df['Name'][k], re.IGNORECASE):
                print(df['Name'][k])
            else:
              print("Name not found")
              break

search_person(keyword, df)

