# -*- coding: utf-8 -*-
"""3c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HiOV5ZRUOZXBgydU0ken87LKdQB5XHVU
"""

import json
import pandas as pd
import requests 
import re


text = input("Enter a name: ")

URL = "https://question-3a-default-rtdb.firebaseio.com/chats.json"

response = requests.get(URL)
data = json.loads(response.text)

data

df = pd.DataFrame(data, columns=['Time', 'Person', 'Message'])
df

text = text.lower()
print(text)

if ' ' in text == True:
    keywords = text.split(' ')

keywords = text

import re

def search_message(keywords, df):
    for i in range(len(keywords)):
        for k in range(len(df)):
            if re.match(keywords[i], df['Person'][k], re.IGNORECASE):
                #print(df['Person'][k])
                print(df['Time'][k],'\t',df['Message'][k])
            else:
              print("Name not found")
              break


search_message(keywords,df)

