# -*- coding: utf-8 -*-
"""1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEGOKbKYQY-lqaG2GSwzyAXer3eBmDpZ
"""

# $Author: Yash Naik

import pandas as pd
import json
import re
import sys


input_file = sys.argv[1]

output_file = sys.argv[2]

#from google.colab import files
#uploaded = files.upload()

df = pd.read_csv(input_file, sep = '\t', header = None)
#df= pd.read_csv('551-0119-updated.txt', sep = '\t', header = None)

df

df.columns = ['Time', 'Person', 'Message']
df

df = df.drop(['Time'], axis=1)
df

df['Person']= df['Person'].str.replace(':','')

df['Message']= df['Message'].str.replace('\r','')

df

dups = df.pivot_table(index = ['Person'], aggfunc ='size') 
dups

new_df = dups.reset_index()

new_df = new_df.rename(columns={'Person': "Person", 0: "Message"})

new_df

output = new_df.to_json(orient = 'records')
parse_to_json = json.loads(output)

"""
with open("json_file", 'w+') as outfile:
    json.dump(parse_to_json, outfile)
"""


with open(output_file, 'w+') as outfile:
    json.dump(parse_to_json, outfile)